baseURL = "https://ardianta.github.io/hugo-fullcalendar/"
languageCode = "en-us"
title = "Hugo Events Calendar with Full Calendar"

buildFuture = true

publishDir = "docs"

[outputs]
    section = ["HTML", "JSON"]
